;; This logfile was generated automatically by `xindy'
;; at 13.02.2016  19:41:48
;; Indexstyle: "C:\\Users\\tom\\Downloads\\Cerner Reference Guide\\62PDy6_D5j", Rawindex: "C:\\Users\\tom\\Downloads\\Cerner Reference Guide\\DQsP9AFlsP", Output: "CernerTrainingManual.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "Ã—" -> "D"
Letter-group: "»Ë¼" -> "M"
Letter-group: "œ¨¼" -> "F"
Letter-group: "€Ë—" -> "A"
Letter-group: "ÃËå" -> "O"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "€Ë—" -> "A"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "Ã—" -> "D"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "œ¨¼" -> "F"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "»Ë¼" -> "M"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "ÃËå" -> "O"